### ISSUE TITLE
Update copyright date

### ISSUE THREAD

**Issue by williambelle** [healthonnet/hon-kconnect-chrome-extension#20]
Here:
* https://github.com/healthonnet/HON-Health-Trust-Indicator/blob/cf134ee1ea3700623f7ad0880e708feedd79b8fb/app/popup.html#L46
* https://github.com/healthonnet/HON-Health-Trust-Indicator/blob/cf134ee1ea3700623f7ad0880e708feedd79b8fb/app/about.html#L203

**Comment by Adrion** [comment]
Added within next release
