### ISSUE TITLE
Yahoo uses tracking links in results

### ISSUE THREAD

**Issue by williambelle** [healthonnet/hon-kconnect-chrome-extension#23]
<img width="662" alt="yahoo" src="https://user-images.githubusercontent.com/2843501/28498144-0d1bfef6-6f98-11e7-9d5e-0083a764c543.png">

**Comment by Adrion** [comment]
I tried some workarounds but didn't work. It's strange manually links are corrects.
old brother is trying to watch you.

**Comment by Adrion** [comment]
For now I disable the behavior we still have to find a way to get the correct link.
