### ISSUE TITLE
Transparency principle x 2 ?

### ISSUE THREAD

**Issue by williambelle** [healthonnet/hon-kconnect-chrome-extension#26]
Is it normal that the Transparency principle appears twice ?

See: 

https://github.com/healthonnet/HON-Health-Trust-Indicator/blob/9ce39df0c437f8731d07fc8eef3ef5d27558e192/app/scripts/popup.js#L5-L7

From https://github.com/healthonnet/Kconnect-search/pull/135

![logo](https://github.com/healthonnet/Kconnect-search/blob/f0c435b6751d517f8d41447b9ffc1968a8f1c66c/src/assets/images/extension/type7.png?raw=true)

**Comment by Adrion** [comment]
Wow how didn't we see it ?! 
Thank you !
